### ISSUE TITLE
Live Display

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#19]
As a user, I would like to see an output that automatically refreshes each button press.

[SP: 13]
[Priority: 7]
[Risk: high]

**Comment by ModestosV** [comment]
- [x] Show mock-up @ModestosV
- [x] Handle Invalid Equations #70 @ModestosV
- [x] Live Display for MainActivity #71 @ModestosV
- [x] Live Display for UnitConversion #72 @ModestosV
- [x] Tests for Live Display #73  @ModestosV
- [x] Acceptance Test @ModestosV

**Comment by ModestosV** [comment]
![snapchat-197479491](https://user-images.githubusercontent.com/17323945/37992768-ac6167da-31da-11e8-954f-b1fc5e1b4793.jpg)

**Comment by ModestosV** [comment]
![snapchat-197479491](https://user-images.githubusercontent.com/17323945/37992815-c569e72a-31da-11e8-9178-2b6390c26998.jpg)

**Comment by ModestosV** [comment]
![image](https://user-images.githubusercontent.com/17323945/38449425-da319d06-39dc-11e8-8536-a5bc2e3ba1da.png)
