### ISSUE TITLE
Convert Between Units

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#20]
As a user, I would like to convert between various units of measurement.

[SP: 21]
[Priority: 4]
[Risk: low]

**Comment by marcdragon123** [comment]
Can we break this task into sub tasks?

**Comment by marcdragon123** [comment]
- [x] Make a menu for the Conversion @marcdragon123 @Aboumicho @mikebasdeo #56 
- [x] Create a backend to calculate the conversion @marcdragon123 @lambhunter0 #57 @ModestosV
- [x] Add all this stuff to the main menu @Arkondoma #58 @ModestosV
- [x] Add remaining conversion choices to onItemSelected() @ModestosV
- [x] Add remaining unit choices to ConversionChoiceList @ModestosV
- [x] Add input/output TextViews that connect to unitList @marcdragon123 @Aboumicho  #57 @ModestosV
- [x] Update color scheme in activity_unit_conversion.xml to match new UI
- [x] Persist data from MainActivity using Bundles

**Comment by Aboumicho** [comment]
Here is one mockup for the unit converter. 
![29216114_10156345894103628_4510756872541700096_o](https://user-images.githubusercontent.com/21128297/37437578-4bdd77c0-27c4-11e8-913d-3ba7d7e32bd4.jpg)

**Comment by Arkondoma** [comment]
Currently all the conversion values are being stored in [LengthConversion.kt](https://github.com/ModestosV/Simple-Calculator-DreamTeam/blob/3e428b4b2db6c73ff5b2c7be12891141da6bba9c/app/src/main/kotlin/com/simplemobiletools/calculator/conversions/LengthConversion.kt) for convenience, but this means it could theoretically be possible to convert from Hours to Pounds (for example), this shouldn't be a problem because spinners enforce what units are being converted, but we should probably split it up at some point

**Comment by ModestosV** [comment]
See: https://github.com/ModestosV/Simple-Calculator-DreamTeam/commit/0c14d17e2fb3cc5ccfd164fcb55bee975362fa37

**Comment by marcdragon123** [comment]
Acceptance Tests
![image](https://user-images.githubusercontent.com/14812262/37573493-d85eb970-2aee-11e8-9033-c39083edfc4e.png)
