### ISSUE TITLE
Binary Manipulation

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#21]
As a user, I would like to convert numbers to/from binary and perform binary arithmetic.
[SP: 34]
[Priority: 4]
[Risk: medium]

**Comment by mikebasdeo** [comment]
![binary_1](https://user-images.githubusercontent.com/9420573/38000441-94d6cf2c-31f5-11e8-81c7-34753721bf7d.png)

**Comment by mikebasdeo** [comment]
- [x] Create new keyboard layout #75 @mikebasdeo 
- [x] Create binary display #76 @mikebasdeo @ModestosV
- [x] Implement binary operations #77 @mikebasdeo @marcdragon123 @ModestosV
- [x] Write tests #78 @Aboumicho @ModestosV

**Comment by marcdragon123** [comment]
![image](https://user-images.githubusercontent.com/14812262/38896585-14c56bdc-4261-11e8-9795-848e18e786c7.png)
