### ISSUE TITLE
 Calculator Modes (Keyboards)

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#22]
As a user, I would like to change the functionality of the buttons on my screen.

[SP: 21]
[Priority: 3]
[Risk: medium]

EDIT: We made a decision to split this feature into 2. This issue shall focus on the actual functionality of the feature and is therefore still ongoing. All the progress so far has been on the base layout and how it incorporates new buttons and colors. A separate issue #54 and story will be created for the mentioned improvements.

**Comment by noahcharbelhayek** [comment]
This prototype illustrates how the shift button changes the layout of the app.
![simplecalculator](https://user-images.githubusercontent.com/14878569/36080953-0fd40f44-0f66-11e8-9b92-06de89081725.png) ![simplecalculator shift](https://user-images.githubusercontent.com/14878569/36080952-0fac1ef8-0f66-11e8-9d99-f7048ee91549.png)

**Comment by ModestosV** [comment]
**EDIT: These subtasks are now relevant to issue #54. Subtasks related to this issue will be re-created in a comment below. They are kept here for historical reasons, but are not up-to-date.**

**Subtasks**
[COMPLETE] 1: Create a mock-up, outlining the new UI @NoahCF
[COMPLETE] 2: Modify the UI @mikebasdeo @ModestosV
[COMPLETE] 3: Add Listeners to new UI buttons @mikebasdeo @ModestosV
[COMPLETE] 4: Add backend tests @lambhunter0 
[COMPLETE] 4.1: Add Android tests @ModestosV
5: Write acceptance test: @ModestosV

**Comment by ModestosV** [comment]
Placement of primary buttons
![28458803_10160155583970066_997939584_n](https://user-images.githubusercontent.com/17323945/36638441-2ae2000e-19c3-11e8-8105-05ba5536a6b8.jpg)

**Comment by ModestosV** [comment]
Do we hardcode colors for shift and clear/delete like the prototype? If so, we will have to account for each color scheme.

**Comment by ModestosV** [comment]
We need to give the users an option of degrees vs radians @mikebasdeo

**Comment by mikebasdeo** [comment]
![calculator_updated](https://user-images.githubusercontent.com/9420573/36797092-22944506-1c75-11e8-8984-bffbfcdff6ff.png)

This is the current state of the UI in branch ModestosV/CalculatorModes.

**Comment by ModestosV** [comment]
**Subtasks**

- [x] Create mock-up for how the 2 views will look @NoahCF 
- [x] Create Shift button that toggles between 2 views @mikebasdeo @ModestosV
- [x] Add UI buttons to both views @ModestosV @NoahCF 
- [x] Implement buttons to work within equations @ModestosV
- [x] Write UI Espresso tests @ModestosV @Arkondoma
- [x] Write Acceptance tests @lambhunter0

**Comment by lambhunter0** [comment]
![screen shot 2018-03-19 at 5 08 03 pm](https://user-images.githubusercontent.com/10935055/37622484-1c269534-2b98-11e8-93ae-bc6289ecc075.png)
