### ISSUE TITLE
Enhanced Main Layout

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#54]
As a user, I would like a more modern layout, which contains more buttons and more intuitive color schemes.

[SP: 34]
[Priority: 1]
[Risk: high]

See issue #22 for the progress that was already made for this feature. In essence, this feature has already been started and is near completion.

**Comment by ModestosV** [comment]
**Subtasks**

- [x] Create a mock-up, outlining the new UI @NoahCF
- [x] Modify the UI @mikebasdeo @ModestosV
- [x] Add Listeners to new UI buttons @ModestosV
- [x] Add backend tests @lambhunter0
- [x] Add Android tests @NoahCF
- [x] Write acceptance test: @lambhunter0

**Comment by lambhunter0** [comment]
![screen shot 2018-03-19 at 5 05 53 pm](https://user-images.githubusercontent.com/10935055/37622355-cf273856-2b97-11e8-9d76-fe675ad3c321.png)

**Comment by noahcharbelhayek** [comment]
![simplecalculator shift](https://user-images.githubusercontent.com/14878569/37623109-f41827b8-2b99-11e8-8329-1f0d7e260919.png)
![simplecalculator](https://user-images.githubusercontent.com/14878569/37623110-f42aeba0-2b99-11e8-8578-b58e101a58cd.png)
