### ISSUE TITLE
Enhanced Main Layout

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#68]
As a user, I would like to know what my 2nd functions are without pressing SHIFT in addition to having the UnitConversion and BinaryManipulation activity available by swiping,

[SP: 55]
[Priority: 1]
[Risk: high]

**Comment by ModestosV** [comment]
- [x] Prototype Layout @mikebasdeo in #88
- [x] Tabs for our 3 main activities (Base Calculator, Main Calculator, Unit Conversion) #88 
- [x] Navigate with tabs #89 
- [x] Navigate with swipe #90 
- [x] UI and Unit Tests #91 
- [x] Acceptance Test @marcdragon123

**Comment by marcdragon123** [comment]
![image](https://user-images.githubusercontent.com/14812262/38896656-51fdf53c-4261-11e8-8330-9f02ff66c6aa.png)
