### ISSUE TITLE
Stats on History Entries

### ISSUE THREAD

**Issue by Arkondoma** [ModestosV/Simple-Calculator-DreamTeam#85]
As a user, I would like basic statistics to be shown in the History Activity.

[SP: 8]
[Priority:  5]
[Risk: low]

**Comment by ModestosV** [comment]
- [ ] Prototype Stats @NoahCF 
- [x] Modify HistoryActivityLayout #92 @ModestosV
- [x] Implement stats #93 @ModestosV
- [x] UI and unit tests #94  @lambhunter0 
- [x] Acceptance Test @marcdragon123

**Comment by marcdragon123** [comment]
![image](https://user-images.githubusercontent.com/14812262/38899909-73f9ecf8-4267-11e8-857d-44f7a408076c.png)
